### PR TITLE
occt76 manual migration + bump to 9.8.0.2

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [x] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
@conda-forge-admin, please rerender

**Comment by Tobias-Fischer** [comment]
This is ready for review @looooo

**Comment by Tobias-Fischer** [comment]
Fix #54 #58

**Comment by looooo** [comment]
@trelau is your smesh 9.8.0.2 ready to be released?

**Comment by trelau** [comment]
@looooo i have a release tag here https://github.com/trelau/SMESH/releases/tag/v9.8.0.2

I only have a few unit tests in SMESH, but as far as I know it's ready

**Pull request merged**
