### PR TITLE
Manual VTK 9.1.0 and OCCT 7.6 migration

### PR DESCRIPTION
**Pull request by basnijholt**
Checklist
* [ ] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [ ] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [ ] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [ ] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by whophil** [comment]
Hi @basnijholt and @looooo , I'm just wondering where this PR stands (and relation to https://github.com/conda-forge/smesh-feedstock/pull/55). My motivation is to advance the VTK 9.1.0 migration. Thanks!

**Comment by basnijholt** [comment]
@whophil, this is currently blocked unfortuntaly. @trelau said here https://github.com/trelau/SMESH/issues/54#issuecomment-1059808352 that he will get to it at some point.

**Comment by whophil** [comment]
> @whophil, this is currently blocked unfortuntaly. @trelau said here [trelau/SMESH#54 (comment)](https://github.com/trelau/SMESH/issues/54#issuecomment-1059808352) that he will get to it at some point.

Thanks for the overview @basnijholt , I'll go check out what's happening upstream!

**Comment by Tobias-Fischer** [comment]
This is fixed by #59

**Pull request closed without merging**
